name: Build Windows EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install pyinstaller requests flask

      - run: pyinstaller --onefile main.py

      - uses: actions/upload-artifact@v4
        with:
          name: NWapp_Win_Exe
          path: dist/*.exe
